### ISSUE TITLE
pine test-merges script failing

### ISSUE THREAD

**Issue by dmose** [mozilla/activity-stream#2630]
```

> Export of 68bc121b28d49f7f99bc30b1eb41932491f73364 from mozilla/activity-stream: file not tracked!
> Error: hg commit failed, output: abort: More links for Pocket
> 
> Export of 68bc121b28d49f7f99bc30b1eb41932491f73364 from mozilla/activity-stream: file not tracked!
> 
>     at shelljs.exec (/Users/dmose/r/as-pine-testing/activity-stream/bin/test-merges.js:188:18)
>     at /Users/dmose/r/as-pine-testing/activity-stream/node_modules/shelljs/src/exec.js:204:9
>     at ChildProcess.exithandler (child_process.js:212:5)
>     at emitTwo (events.js:106:13)
>     at ChildProcess.emit (events.js:194:7)
>     at maybeClose (internal/child_process.js:899:16)
>     at Socket.<anonymous> (internal/child_process.js:342:11)
>     at emitOne (events.js:96:13)
>     at Socket.emit (events.js:191:7)
>     at Pipe._handle.close [as _onclose] (net.js:511:12)

```

I think what's going on here is that if, for whatever reason, a PR adding a file to the repo gets skipped, all subsequent attempts to push changes to that file confuse hg.  Probably the simplest thing to do is just make sure merges are handled in chronological order, and then go fill in any holes in the history.

**Comment by dmose** [comment]
This actually turned out to be a shell quoting problem, fixed by using a version of exec that doesn't go through the shell.
