### ISSUE TITLE
Perma-orange No marks with the name topsites_first_painted_ts at getMostRecentAbsMarkStartByName

### ISSUE THREAD

**Issue by Mardak** [mozilla/activity-stream#2981]
This is failing across a number of tests probably any that open new tabs:
```
 FAIL | browser/components/resistfingerprinting/test/browser/browser_netInfo.js | uncaught exception
Error: No marks with the name topsites_first_painted_ts at getMostRecentAbsMarkStartByName@resource://activity-stream/data/content/activity-stream.bundle.js:507:13 _sendPaintedEvent@resource://activity-stream/data/content/activity-stream.bundle.js:2367:37 FrameRequestCallback*_onNextFrame/<@resource://activity-stream/data/content/activity-stream.bundle.js:2341:7 FrameRequestCallback*_onNextFrame@resource://activity-stream/data/content/activity-stream.bundle.js:2340:5 _maybeSendPaintedEvent@resource://activity-stream/data/content/activity-stream.bundle.js:2360:5 componentDidUpdate@resource://activity-stream/data/content/activity-stream.bundle.js:2328:5 [6]</a</e.prototype.notifyAll@resource://activity-stream/vendor/react-dom.js:12:7747 close@resource://activity-stream/vendor/react-dom.js:14:18084 closeAll@resource://activity-stream/vendor/react-dom.js:15:9522 perform@resource://activity-stream/vendor/react-dom.js:15:9014 perform@resource://activity-stream/vendor/react-dom.js:15:8934 perform@resource://activity-stream/vendor/react-dom.js:14:24406 T@resource://activity-stream/vendor/react-dom.js:14:24583 closeAll@resource://activity-stream/vendor/react-dom.js:15:9522 perform@resource://activity-stream/vendor/react-dom.js:15:9014 batchedUpdates@resource://activity-stream/vendor/react-dom.js:14:3912 u@resource://activity-stream/vendor/react-dom.js:14:23624 r@resource://activity-stream/vendor/react-dom.js:14:21389 enqueueSetState@resource://activity-stream/vendor/react-dom.js:14:22386 [6]</r.prototype.setState@resource://activity-stream/vendor/react.js:12:7755 c/</c</c.prototype.onStateChange@resource://activity-stream/vendor/react-redux.js:4:4880 notify@resource://activity-stream/vendor/react-redux.js:4:13870 s</t.prototype.notifyNestedSubs@resource://activity-stream/vendor/react-redux.js:4:14346 c/</c</c.prototype.onStateChange@resource://activity-stream/vendor/react-redux.js:4:4898 dispatch@resource://activity-stream/vendor/redux.js:339:8 messageMiddleware/</<@resource://activity-stream/data/content/activity-stream.bundle.js:747:3 initStore/<@resource://activity-stream/data/content/activity-stream.bundle.js:761:7 Stack trace: chrome://mochikit/content/tests/SimpleTest/SimpleTest.js:simpletestOnerror:1652
 FAIL | browser/components/resistfingerprinting/test/browser/browser_navigator.js | uncaught exception
Error: No marks with the name topsites_first_painted_ts at getMostRecentAbsMarkStartByName@resource://activity-stream/data/content/activity-stream.bundle.js:507:13 _sendPaintedEvent@resource://activity-stream/data/content/activity-stream.bundle.js:2367:37 FrameRequestCallback*_onNextFrame/<@resource://activity-stream/data/content/activity-stream.bundle.js:2341:7 FrameRequestCallback*_onNextFrame@resource://activity-stream/data/content/activity-stream.bundle.js:2340:5 _maybeSendPaintedEvent@resource://activity-stream/data/content/activity-stream.bundle.js:2360:5 componentDidUpdate@resource://activity-stream/data/content/activity-stream.bundle.js:2328:5 [6]</a</e.prototype.notifyAll@resource://activity-stream/vendor/react-dom.js:12:7747 close@resource://activity-stream/vendor/react-dom.js:14:18084 closeAll@resource://activity-stream/vendor/react-dom.js:15:9522 perform@resource://activity-stream/vendor/react-dom.js:15:9014 perform@resource://activity-stream/vendor/react-dom.js:15:8934 perform@resource://activity-stream/vendor/react-dom.js:14:24406 T@resource://activity-stream/vendor/react-dom.js:14:24583 closeAll@resource://activity-stream/vendor/react-dom.js:15:9522 perform@resource://activity-stream/vendor/react-dom.js:15:9014 batchedUpdates@resource://activity-stream/vendor/react-dom.js:14:3912 u@resource://activity-stream/vendor/react-dom.js:14:23624 r@resource://activity-stream/vendor/react-dom.js:14:21389 enqueueSetState@resource://activity-stream/vendor/react-dom.js:14:22386 [6]</r.prototype.setState@resource://activity-stream/vendor/react.js:12:7755 c/</c</c.prototype.onStateChange@resource://activity-stream/vendor/react-redux.js:4:4880 notify@resource://activity-stream/vendor/react-redux.js:4:13870 s</t.prototype.notifyNestedSubs@resource://activity-stream/vendor/react-redux.js:4:14346 c/</c</c.prototype.onStateChange@resource://activity-stream/vendor/react-redux.js:4:4898 dispatch@resource://activity-stream/vendor/redux.js:339:8 messageMiddleware/</<@resource://activity-stream/data/content/activity-stream.bundle.js:747:3 initStore/<@resource://activity-stream/data/content/activity-stream.bundle.js:761:7 Stack trace: chrome://mochikit/content/tests/SimpleTest/SimpleTest.js:simpletestOnerror:1652
```
Linux32 opt: https://treeherder.mozilla.org/logviewer.html#?job_id=118236941&repo=pine&lineNumber=4117
Linux64 debug: https://treeherder.mozilla.org/logviewer.html#?job_id=118235456&repo=pine&lineNumber=6436

Most likely regressed by #2936

**Comment by dmose** [comment]
All of these failures seem to be in the resist fingerprinting suite.  I suspect https://bugzilla.mozilla.org/show_bug.cgi?id=1369303 is the smoking gun; next up is to figure out what to do about it.
