### ISSUE TITLE
generated jar.mn can include activity-stream-debug.html twice, breaking pine

### ISSUE THREAD

**Issue by dmose** [mozilla/activity-stream#3752]
#3740 broke the pine build:

```
 0:19.51 Traceback (most recent call last):
 0:19.51   File "/usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 174, in _run_module_as_main
 0:19.51     "__main__", fname, loader, pkg_name)
 0:19.51   File "/usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
 0:19.51     exec code in run_globals
 0:19.51   File "/Users/dmose/r/as-pine-testing/mozilla-central/python/mozbuild/mozbuild/action/process_install_manifest.py", line 111, in <module>
 0:19.51     main(sys.argv[1:])
 0:19.51   File "/Users/dmose/r/as-pine-testing/mozilla-central/python/mozbuild/mozbuild/action/process_install_manifest.py", line 98, in main
 0:19.51     defines=args.defines)
 0:19.51   File "/Users/dmose/r/as-pine-testing/mozilla-central/python/mozbuild/mozbuild/action/process_install_manifest.py", line 64, in process_manifest
 0:19.51     copier, defines_override=defines, link_policy=link_policy
 0:19.51   File "/Users/dmose/r/as-pine-testing/mozilla-central/python/mozbuild/mozpack/manifests.py", line 371, in populate_registry
 0:19.51     registry.add(dest, cls(entry[1]))
 0:19.51   File "/Users/dmose/r/as-pine-testing/mozilla-central/python/mozbuild/mozpack/copier.py", line 69, in add
 0:19.51     return errors.error("%s already added" % path)
 0:19.51   File "/Users/dmose/r/as-pine-testing/mozilla-central/python/mozbuild/mozpack/errors.py", line 106, in error
 0:19.51     self._handle(self.ERROR, msg)
 0:19.51   File "/Users/dmose/r/as-pine-testing/mozilla-central/python/mozbuild/mozpack/errors.py", line 98, in _handle
 0:19.51     raise ErrorMessage(msg)
 0:19.51 mozpack.errors.ErrorMessage: Error: chrome/content/data/content/activity-stream-debug.html already added
```

**Comment by dmose** [comment]
Not only did I have to clean out my mozilla-central tree (which I had tried before), I also had to clean out the local github tree.  It has worked once now.  If this keeps working, I'll close the bug in a day or so.

**Comment by Mardak** [comment]
This is probably because your git repository has an untracked `system-addon/data/content/activity-stream-debug.html` file that needs to be removed.
