### ISSUE TITLE
pine script blowing up saying activity-stream-initial-state.js has already been added

### ISSUE THREAD

**Issue by dmose** [mozilla/activity-stream#3853]
Also see https://bugzilla.mozilla.org/show_bug.cgi?id=1417626

Blowing away mozilla-central and repulling it did not fix the problem.  Investigating further...
``` 0:58.74 Elapsed: 0.00s; From /Users/dmose/r/as-pine-testing/mozilla-central/objdir-frontend/dist/bin/browser/localization: Kept 1 existing; Added/updated 0; Removed 0 files and 0 directories.
 0:58.82 Traceback (most recent call last):
 0:58.82   File "/usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 174, in _run_module_as_main
 0:58.82     "__main__", fname, loader, pkg_name)
 0:58.82   File "/usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
 0:58.82     exec code in run_globals
 0:58.82   File "/Users/dmose/r/as-pine-testing/mozilla-central/python/mozbuild/mozbuild/action/process_install_manifest.py", line 111, in <module>
 0:58.82     main(sys.argv[1:])
 0:58.82   File "/Users/dmose/r/as-pine-testing/mozilla-central/python/mozbuild/mozbuild/action/process_install_manifest.py", line 98, in main
 0:58.82     defines=args.defines)
 0:58.82   File "/Users/dmose/r/as-pine-testing/mozilla-central/python/mozbuild/mozbuild/action/process_install_manifest.py", line 45, in process_manifest
 0:58.82     remove_unaccounted.add(p, dummy_file)
 0:58.82   File "/Users/dmose/r/as-pine-testing/mozilla-central/python/mozbuild/mozpack/copier.py", line 69, in add
 0:58.82     return errors.error("%s already added" % path)
 0:58.82   File "/Users/dmose/r/as-pine-testing/mozilla-central/python/mozbuild/mozpack/errors.py", line 106, in error
 0:58.82     self._handle(self.ERROR, msg)
 0:58.83   File "/Users/dmose/r/as-pine-testing/mozilla-central/python/mozbuild/mozpack/errors.py", line 98, in _handle
 0:58.83     raise ErrorMessage(msg)
 0:58.83 mozpack.errors.ErrorMessage: Error: chrome/content/prerendered/static/activity-stream-initial-state.js already added
```

**Comment by Mardak** [comment]
Could be https://bugzilla.mozilla.org/show_bug.cgi?id=1417626

Regressed by https://bugzilla.mozilla.org/show_bug.cgi?id=1416465

**Comment by Mardak** [comment]
Indeed. Reverting the change fixes this for me:

```sh
curl https://hg.mozilla.org/mozilla-central/raw-rev/6f0e650b0e53 | patch -Rp1
```

**Comment by dmose** [comment]
Good times!  Thanks for tracking down.  I guess we could add a mozilla-central-patch to workaround the problem, but I'm inclined to just wait and see if they jump on this and fix it quickly before doing that.

**Comment by Mardak** [comment]
This has been directly backed out from mozilla-central:
https://bugzilla.mozilla.org/show_bug.cgi?id=1416465#c17
https://hg.mozilla.org/mozilla-central/rev/a3f183201f7f
