### ISSUE TITLE
test-merges.js (pine script) should handle tree closings more gracefully

### ISSUE THREAD

**Issue by dmose** [mozilla/activity-stream#3856]
Right now, just spews an error message every time its run from cron, which stack up and make it easier to miss real error messages.  If we can't detect that the reason the push failed was tree closure from an exit code (which I suspect we won't be able to), we can probably just do it with a regexp.

Example error spewage:
```
 2:33.99 Your build was successful!
To view resource usage of the build, run |mach resource-usage|.
To take your build for a test drive, run: |mach run|
For more information on what to do now, see https://developer.mozilla.org/docs/Developer_Guide/So_You_Just_Built_Firefox
Committing exported f959fdd6963c29e2a648bd4eb14c053b7fef8582 to activity-stream...
pushing to ssh://hg.mozilla.org/projects/pine
remote: Warning: the RSA host key for 'hg.mozilla.org' differs from the key for the IP address '63.245.215.102'
remote: Offending key for IP in /Users/dmose/.ssh/known_hosts:21
remote: Matching host key in /Users/dmose/.ssh/known_hosts:27
no revisions specified to push; using . to avoid pushing multiple heads
searching for changes
remote: adding changesets
remote: adding manifests
remote: adding file changes
remote: added 1 changesets with 2 changes to 133 files (+1 heads)
remote:
remote:
remote: ************************** ERROR ****************************
remote: pine is CLOSED! Reason: windows cloning issues bug 1417881
remote: To push despite the closed tree, include "CLOSED TREE" in your push comment
remote: *************************************************************
remote:
remote:
remote: transaction abort!
remote: rollback completed
remote: pretxnchangegroup.a_treeclosure hook failed
Stripping tip commit from mozilla-central so the next artifact build will work ...
Error: pushToHgProjectBranch failed; tip stripped from hg
    at pushToHgProjectBranch.catch (/Users/dmose/r/as-pine-testing/activity-stream/bin/test-merges.js:293:13)
    at process._tickCallback (internal/process/next_tick.js:109:7)
Something went wrong processing the merges: Error: pushToHgProjectBranch failed; tip stripped from hg
    at pushToHgProjectBranch.catch (/Users/dmose/r/as-pine-testing/activity-stream/bin/test-merges.js:293:13)
    at process._tickCallback (internal/process/next_tick.js:109:7)
127 files updated, 0 files merged, 6 files removed, 0 files unresolved
saved backup bundle to /Users/dmose/r/as-pine-testing/mozilla-central/.hg/strip-backup/569d79d13a4c-ba707834-backup.hg
```

**Comment by Mardak** [comment]
Moved to https://bugzilla.mozilla.org/show_bug.cgi?id=1448366
